[algokit]
min_version = "v1.12.1"

[project]
type = "python"

[scripts]
bootstrap = "algokit project bootstrap poetry"
deploy = "cd backend && poetry run python deploy.py"

[generate.devcontainer]
description = "Generate a default 'devcontainer.json' configuration that pre-installs algokit and launches Algorand sandbox as part of codespace container provisioning."
path = ".algokit/generators/create-devcontainer"
